version: '2'
services:
 traefik:
    build: ./traefik
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

 redis:
  image: redis
  container_name: cache
  expose:
    - 6379

 api:
  build: ./api
  links:
    - redis
  environment:
    - REDIS_URL=redis://cache
    - PORT=8091
  labels:
      - traefik.enable=true
      - "traefik.frontend.rule=PathPrefixStrip: /api/"
#      - "traefik.frontend.rule=Host:localhost, 127.0.0.1; PathPrefixStrip: /api"

 home:
  build: ./home
  environment:
    - PORT=8090
  labels:
      - traefik.enable=true
      - "traefik.frontend.rule=PathPrefixStrip: /"
#      - "traefik.frontend.rule=Host:localhost"

