[entryPoints]
  [entryPoints.http]
    address = ":80" # will be overriden

[frontends]
  [frontends.frontend1]
  backend = "backend1"
  
  [frontends.frontend2]
  backend = "backend2"
    [frontends.frontend2.routes.test_1]
      rule = "PathPrefixStrip: /api/"
  
[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://heroku-home.asdrubalds.com.ve/"
  [backends.backend2]
    [backends.backend2.servers.server1]
    url = "http://heroku-api.asdrubalds.com.ve/"
